/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '864px',
      lg: '1080px',
      xl: '1280px',
      '2xl': '1440px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1.5rem',
        sm: '2rem',
        lg: '3rem',
        xl: '3.5rem',
      },
      screens: {
        xs: '480px',
        sm: '640px',
        md: '864px',
        lg: '1080px',
        xl: '1280px',
        '2xl': '1440px',
      },
    },
    extend: {
      colors: {
        'atelier-paper': '#F9F5ED',
        'atelier-parchment': '#F1E7D8',
        'atelier-sand': '#E3D2BA',
        'atelier-haze': '#D8CCBA',
        'atelier-mist': '#F2ECE4',
        'atelier-clay': '#C98A5B',
        'atelier-terracotta': '#B65C38',
        'atelier-terracotta-strong': '#9A4726',
        'atelier-ink': '#2C2622',
        'atelier-ink-soft': '#473F38',
        'atelier-shadow': '#4F463D',
        'atelier-charcoal': '#1F1A16',
        'atelier-night': '#15120F',
        'atelier-moss': '#5F7042',
        'atelier-moss-strong': '#46572E',
        'atelier-sage': '#8E9871',
        'atelier-sun': '#D38A31',
        'atelier-berry': '#824039',
        'atelier-berry-strong': '#6B2F2A',
        'atelier-highlight': '#F6C85F',
      },
      fontFamily: {
        sans: [
          '"Work Sans"',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'sans-serif',
        ],
        display: ['"Fraunces"', 'Georgia', '"Times New Roman"', 'serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        xs: ['0.8125rem', { lineHeight: '1.35' }],
        sm: ['0.875rem', { lineHeight: '1.45' }],
        base: ['1rem', { lineHeight: '1.6' }],
        lg: ['1.125rem', { lineHeight: '1.55' }],
        xl: ['1.25rem', { lineHeight: '1.45' }],
        '2xl': ['1.5rem', { lineHeight: '1.4' }],
        '3xl': ['1.875rem', { lineHeight: '1.35' }],
        '4xl': ['2.25rem', { lineHeight: '1.2' }],
      },
      borderRadius: {
        xl: '1.25rem',
        '2xl': '1.75rem',
        '3xl': '2.25rem',
      },
      spacing: {
        13: '3.25rem',
        15: '3.75rem',
        18: '4.5rem',
        22: '5.5rem',
        26: '6.5rem',
        30: '7.5rem',
      },
      boxShadow: {
        notebook: '0 18px 40px -28px rgba(21, 18, 15, 0.45)',
        'focus-atelier': '0 0 0 3px rgba(182, 92, 56, 0.35)',
      },
    },
  },
  plugins: [],
};
